[datasets]
sergio_tgt_test = "/mnt/polished-lake/home/nkondapaneni/state/simulate/sergio/data/sergio_synthetic/SERGIO_TGT_test_merged"

[training]

[zeroshot]
"sergio_tgt_test.BA-VM_size010_seed0100" = "test"
"sergio_tgt_test.BA-VM_size010_seed0101" = "test"
"sergio_tgt_test.BA-VM_size010_seed0102" = "test"
"sergio_tgt_test.BA-VM_size010_seed0103" = "test"
"sergio_tgt_test.BA-VM_size050_seed0100" = "test"
"sergio_tgt_test.BA-VM_size050_seed0101" = "test"
"sergio_tgt_test.BA-VM_size050_seed0102" = "test"
"sergio_tgt_test.BA-VM_size050_seed0103" = "test"
"sergio_tgt_test.BA-VM_size100_seed0100" = "test"
"sergio_tgt_test.BA-VM_size100_seed0101" = "test"
"sergio_tgt_test.BA-VM_size100_seed0102" = "test"
"sergio_tgt_test.BA-VM_size100_seed0103" = "test"
"sergio_tgt_test.BA_size010_seed0100" = "test"
"sergio_tgt_test.BA_size010_seed0101" = "test"
"sergio_tgt_test.BA_size010_seed0102" = "test"
"sergio_tgt_test.BA_size010_seed0103" = "test"
"sergio_tgt_test.BA_size050_seed0100" = "test"
"sergio_tgt_test.BA_size050_seed0101" = "test"
"sergio_tgt_test.BA_size050_seed0102" = "test"
"sergio_tgt_test.BA_size050_seed0103" = "test"
"sergio_tgt_test.BA_size100_seed0100" = "test"
"sergio_tgt_test.BA_size100_seed0101" = "test"
"sergio_tgt_test.BA_size100_seed0102" = "test"
"sergio_tgt_test.BA_size100_seed0103" = "test"
"sergio_tgt_test.ER_size010_seed0100" = "test"
"sergio_tgt_test.ER_size010_seed0102" = "test"
"sergio_tgt_test.ER_size010_seed0103" = "test"
"sergio_tgt_test.ER_size050_seed0100" = "test"
"sergio_tgt_test.ER_size050_seed0101" = "test"
"sergio_tgt_test.ER_size050_seed0102" = "test"
"sergio_tgt_test.ER_size050_seed0103" = "test"
"sergio_tgt_test.ER_size100_seed0100" = "test"
"sergio_tgt_test.ER_size100_seed0101" = "test"
"sergio_tgt_test.ER_size100_seed0102" = "test"
"sergio_tgt_test.ER_size100_seed0103" = "test"
