wandb_track: true
weight_decay: 0.0005
batch_size: 64
lr: 0.001
max_steps: 100000
train_seed: 42
val_freq: 2000
ckpt_every_n_steps: 4000
gradient_clip_val: 10
gradient_accumulation_steps: 1
loss_fn: mse
devices: 1
strategy: auto
use_mfu: true
mfu_kwargs:
    available_flops: 60e12
    use_backward: true
    logging_interval: 10
    window_size: 2
cumulative_flops_use_backward: true
